### ISSUE TITLE
Volume controls

### ISSUE THREAD

**Issue by luanpotter** [luanpotter/audioplayer#1]
I just realized issues were not available because you need to turn them manually on a fork! Sorry, everyone!

[Paul](https://github.com/pauldemarco) has made an awesome [fork](https://github.com/pauldemarco/audioplayer) to allow volume controls! That's very important to [flame](https://github.com/luanpotter/flame), thanks, man!

I'd like to pull request you in, but now we are working on iOS as well. I know it's a hassle, I myself have no iDevices to test with. Would you be able to patch the swift code as well? Then we can merge!

(I'm creating this issue here because @pauldemarco hasn't enabled issues in his fork either (dang it, GitHub!).

**Comment by pauldemarco** [comment]
Volume control added for iOS.

**Comment by luanpotter** [comment]
Great! Merged into master! Thanks, @pauldemarco ^.^
