### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by FelschR** [luanpotter/audioplayer#10]
Android's media player allows looping the audio with:
```java
mediaPlayer.setLooping(true);
```

It would be nice if you could integrate this functionality.

**Comment by luanpotter** [comment]
That`s a good idea; currently what [flame](https://github.com/luanpotter/flame) does to allow this is the following:

```dart
  Future<AudioPlayer> loop(String fileName, { volume: 1.0 }) async {
    File file = await load(fileName);
    AudioPlayer player = new AudioPlayer();
    player.setCompletionHandler(() => player.play(file.path, isLocal: true, volume: volume));
    return await player..play(file.path, isLocal: true);
  }
```

A completion handler that replays the sound. It'd be nice to have a native option to do it; we just need to consider if it is as easy on iOS. If you'd like, please consider submitting a PR ;)

Thanks so much for the contributions, and sorry for the delay!

**Comment by luanpotter** [comment]
This was added on 0.6.0.
