### ISSUE TITLE
Bug trying to play audio file

### ISSUE THREAD

**Issue by matejthetree** [luanpotter/audioplayer#12]
https://gist.github.com/matejthetree/4a51db293b6966696a97593c40a7f202

`    _audioPlayer.play("sounds/metronome.wav");
`

This is how I call it.

What could it be, does the plugin supports wav?

**Comment by luanpotter** [comment]
Is that the path of the file on the device? I had a lot of confusion on the beginning, but audioplayers plays audios from the device, not from your assets on your pubfile. If you'd like to do the latter, you can do exactly as [flame](https://github.com/luanpotter/flame/blob/master/lib/audio.dart) does it; basically copy the file to the device and then play it:

```dart
  Future<ByteData> _fetchAsset(String fileName) async {
    return await rootBundle.load('assets/audio/' + fileName);
  }

  Future<File> _fetch(String fileName) async {
    final file = new File('${(await getTemporaryDirectory()).path}/$fileName');
    return await file.writeAsBytes((await _fetchAsset(fileName)).buffer.asUint8List());
  }

  Future<AudioPlayer> play(String fileName, { volume: 1.0 }) async {
    File file = await _fetch(fileName);
    return await new AudioPlayer()..play(file.path, isLocal: true, volume: volume);
  }
```

For more details, check the whole file in the link I provided. That's the complete code for flame's audio handling. Note the isLocal flag, which you can set to false, but that's doesn't mean it will get files from your pubspec, but rather online. Also don't forget to add the sound to the pubspec file itself in the assets and run a `flutter pub get` to update, otherwise it won't be accessible.

It does seem to support WAV, on Android at least.

If the file you are trying to access is indeed in the device, then there is a problem and I can further look into it. Maybe try an absolute URL in this case, to see if it's a path problem.

Thanks for your feedback!

**Comment by matejthetree** [comment]
Thank you.

Do you think this could be done as a separate package for ones who do basic assets audio import?
To have it as an option, and to extract it from flame?

Gonna try the solution now.

**Comment by matejthetree** [comment]
I love your audio library in flame. If you need help, I can help to make a package of audio, and update flame to use it as a package. Only thing I see, is that `'assets/audio/'` should be optionaly set as a audio file prefix, maybe on creation of `Audio`, thus allowing full `fileName` strings.

**Comment by matejthetree** [comment]
Audio plays, but I still get this error
https://gist.github.com/matejthetree/de5dd4cbed55cfdbe4f598a87764e625

**Comment by matejthetree** [comment]
This may be dart 2 type checking

**Comment by luanpotter** [comment]
I think this behavior could be incorporated in the audioplayers lib itself, and not on flame (don't need to create a third lib, IMO: it's a useful feature for anyone who uses this lib). And yes, we make the path as a parameter so that flame can set it appropriately. Then we can also fix the Future problem, and make it ready to work with dart 2 :)

**Comment by luanpotter** [comment]
I will close this issue, because the dart 2 incompatibility was fixed, and open a new one regarding importing Flame's Audio class to here.

**Comment by cnqiuxue** [comment]
E/flutter (18314): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (18314): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (18314): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:24:38)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #2      AudioCache.fetchToMemory (package:audioplayers/audio_cache.dart:54:37)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #3      AudioCache.load (package:audioplayers/audio_cache.dart:72:37)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #4      AudioCache.play (package:audioplayers/audio_cache.dart:87:23)
E/flutter (18314): <asynchronous suspension>
E/flutter (18314): #5      _MyHomePageState.initState (package:flutter_view/main.dart:75:16)
E/flutter (18314): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (18314): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (18314): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (18314): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (18314): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (18314): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (18314): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (18314): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (18314): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (18314): #44     ComponentEl

**Comment by cnqiuxue** [comment]
An error was reported after installing the plug-in
