### ISSUE TITLE
Objective-C or Swift?

### ISSUE THREAD

**Issue by pauldemarco** [luanpotter/audioplayer#3]
Is it now possible to remove the swift dependency on this? I'm getting some errors when using this alongside Firebase plugins.

**Comment by luanpotter** [comment]
I don't know much about iOS; AFAIK, Swift is a better language than the prolix Object-C, and should be backward compatible with any older code (including Firebase plugins). Of course either languages will work, though, so whatever works better for us is fine :)

**Comment by luanpotter** [comment]
The old swift file was deleted due to the aforementioned incompatibilities, so I'm closing this issue. Feel free to re-open if more changes are needed!
