### ISSUE TITLE
Audio only in headphones

### ISSUE THREAD

**Issue by timgrubb** [luanpotter/audioplayer#33]
I seem to be have the issue that I only get audio when I put on headphones. This only happens on my app using the plugin. It seems the issue may have been resolved in the original audioplayer code as referenced here.  https://stackoverflow.com/questions/50616323/flutter-apps-audio-not-working-through-speaker

Thanks

Tim

**Comment by mjordan56** [comment]
I can confirm the problem that Tim reported and have additional information from my testing.

I started investigating an audio playback problem after integrating the flame package into my Flutter app. I was able to successfully play local audio files on an Android emulator of a Pixel 2 XL API 25, on an LG K10 running Android 7.0, and on an iOS simulator of an iPhone 8 running iOS 11.4. But when I tried running on an iPhone X running iOS 11.4.1 the audio didn't play. At least it didn't appear to play as there was no audio sound from the iPhone X.

Digging into this problem further I removed my app from the equation and tried using flame from the barebones initial Flutter app and got the same results; i.e. audio sound played successfully on all my test targets but failed on iPhone X. I then removed flame from the mix and cloned the audioplay code so I could test using the audioplayer example. Once again, the same results where the audio sounds successfully plays on all my target test devices except for the iPhone X. I then compare the console log output from the iPhone 5s to the iPhone X and from everything I could see the iPhone X was playing the audio file yet no sound was coming from the iPhone X. I also tried running my tests on the iOS simulator of an iPhone X device and to my surprise the iOS simulator of an iPhone X successfully played the audio sound.

I tried debugging this problem a little further but was coming up with nothing so I was going to log an issue here. But before I logged a new issue I thought I'd check the outstanding issues and read Tim's open issue "Audio only in headphones #33" and haarts open issue "iOS: AudioCache doesn't play #32." I decided to test if the audio sound was playing on my iPhone X through the headphones. Once I connected a Bluetooth headset to my iPhone X I was able to hear the audio sound being played. (Thanks for the insight, Tim!)

I believe the issue reported by Tim and haarts are the same issue and that Tim has provided information about the solution to the problem. I hope someone is able to use this information to provide a solution for this problem relatively quickly.

BTW, thanks for the audioplayer and flame packages!

Michael

**Comment by tsun424** [comment]
From my testing, speaker mode is only working on Simulator, not on a real iOS device.
I've created a pull request(#41) to fix it.

**Comment by tsun424** [comment]
My testing device is on iOS 10.3.3, it's working after I applied the patch.

**Comment by luanpotter** [comment]
Fixed by #41. Thanks @tsun424!
