### ISSUE TITLE
iOS background mode doesn't work

### ISSUE THREAD

**Issue by nfree** [luanpotter/audioplayer#35]
On iOS, the audio stops when I close the screen. Android works fine.
I enabled the following options in Xcode.

<img width="688" alt="2018-08-29 5 02 46" src="https://user-images.githubusercontent.com/46163/44774201-72e37000-abad-11e8-85d5-b8fa14908cd3.png">

**Comment by luanpotter** [comment]
It should work, I don't know why. Maybe @feroult can help out testing on the iDevices?

**Comment by tsun424** [comment]
From my testing, background mode is only working on Simulator, not on a real iOS device.
I've created a pull request(#41) to fix it.

**Comment by luanpotter** [comment]
Fixed by #41. Thanks @tsun424!
