### ISSUE TITLE
completionHandler is not called in iOS background mode

### ISSUE THREAD

**Issue by ngocdaothanh** [luanpotter/audioplayer#45]
I'm trying to write an iOS app to as a music player:
When a song finishes playing, my completionHandler will be called, and it will set a new song.

It works well when the app is in foreground.
But in background, completionHandler won't be called.

How to fix the problem?

**Comment by ngocdaothanh** [comment]
Sorry this is a false alarm.
`completionHandler` is actually called.

I relied on `didUpdateWidget` to play next song, but it's not called when the app is in background.

**Comment by YaarPatandarAA** [comment]
I am trying to do this exact same thing. 

Have a song playing, when first song finishes play next song.

How I am doing this is when the first song completes I am calling a method which allows me to audioplayer.play(next song url)

However like you state in iOS is app is not in foreground it doesn’t work.
