### ISSUE TITLE
How can use playerid

### ISSUE THREAD

**Issue by samanzamani** [luanpotter/audioplayer#53]
Hi
How can use `playerid` for `play` or `pause` music?

**Comment by luanpotter** [comment]
Hi, @samanzamani !

So, you never need to use the playerId. It's just used internally to orchestrate the communication between Flutter and the native code. In order to control your player, use the player instance itself! E.g.:

```dart
    AudioPlayer player = new AudioPlayer(/* params... */);
    // later...
    player.resume();
    player.pause();
    player.stop();
```

Something like that. Let me know if have any doubts!

**Comment by samanzamani** [comment]
@luanpotter Thanks for the answer.
I try to create an online music player app with flutter and need control music on different page.
Is possible access `AudioPlayer` object after widget dispose !?

**Comment by luanpotter** [comment]
To do that you must create the audio player in a global scope, outside of your component. Or you can create it higher up in the hierarchy of components in order for it to still be accessible when you needed. If you create it inside a component and that component is disposed, the reference goes away to.
