### ISSUE TITLE
Clean & Improve logging

### ISSUE THREAD

**Issue by lukaspili** [luanpotter/audioplayer#54]
Two requests actually:

1. These 2 logs should be silenced, because they print in a loop and pollute the console : https://github.com/luanpotter/audioplayer/blob/95ad75a6ec464a1b06a37b63e2dbd516eedcfc5c/ios/Classes/AudioplayersPlugin.m#L259-L261

2. `AudioPlayer.logEnabled` should toggle the logs on the native sides as well 

Thanks!

**Comment by luanpotter** [comment]
Totally agreed, @lukaspili !

Would you kindly contribute with a PR? Thanks!!

**Comment by luanpotter** [comment]
@jeffmikels just made a PR that clean a bit of the excessive logging (thanks!). Is it enough or do we have more cleanup to do?

**Comment by lukaspili** [comment]
Hello @luanpotter, @jeffmikels 
This is enough as it clears the log that were called in a loop.
Thanks for taking care of this :)
